import Head from 'next/head'
import Script from 'next/script'
 
export default function Home() {
  return (
    <>
      <Head>
        <title>rmphost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></Script>

      <section id="Hero_part">
        <div class="container finishss">
            <div class="row heros_row">
                <div class="col-lg-7 m-0 p-0">
                 <div class="hero_left">
                    <h1>We Will Help Your Business
                        <span>Grow 2x</span> Times Using Our Best Technologies</h1>

                        <p>Welcome To rpmhost
                          rpmhost is a Professional software and website agency Platform. Here we will provide you only interesting content, which you will like very much. Were dedicated to providing you the best of software and website agency. </p>
                 </div>
                </div>
                <div class="col-lg-5">
                    <div class="hero_right">
                        <img src="image/banner1.png" alt="" srcset="" />
                    </div>
                    <div class="finish_projects">
                      <p>150 <span>+</span> </p>
                      <h6>Finish Projects</h6>
                    </div>
                </div>
            </div>
        </div>
    </section>

    </>
  )
}
